// The keyword map: every planned page, the search terms it targets and the
// angle that keeps it different from its neighbours. One primary query per
// page, so pages never compete with each other for the same search.
//
// scripts/check-content.mjs uses this to accept links to planned pages.

export const STATIC_ROUTES = [
  "/",
  "/about",
  "/services",
  "/website-developer",
  "/industries",
  "/blog",
  "/pricing",
  "/process",
  "/faq",
  "/contact",
  "/careers",
  "/privacy",
  "/free-website",
  "/subscribe",
  "/technologies",
  "/hire-developers",
  "/glossary",
  "/resources",
  "/sitemap"
];

// Hand-written pages added after the first plan, with the query each owns.
export const STATIC_TARGETS = [
  { path: "/hire-developers", primary: "hire dedicated developers", also: ["dedicated development team", "hire developers in nepal", "offshore development team", "staff augmentation"], angle: "The Embedded model as a product: roles, how the first two weeks run, overlap hours, ownership, how it compares with freelancers and agencies." },
  { path: "/glossary", primary: "web development glossary", also: ["seo glossary", "what is aeo", "what is geo", "digital marketing terms"], angle: "Short, quotable definitions of the terms on our pages, each linking to the guide or service that goes deeper. Built for answer engines." },
  { path: "/resources", primary: "web development resources", also: ["website guides", "seo guides for small business"], angle: "Hub: guides by category, glossary, FAQ, free website design, newsletter." },
  { path: "/technologies", primary: "technology stack", also: ["web development technologies", "software development stack"], angle: "Hub: the stack we build with and when each part is the right choice." }
];

export const SERVICES = [
  { slug: "web-development", title: "Web development", primary: "web development company", also: ["web development services", "custom web development", "web application development"], angle: "Full custom websites and web apps: Next.js, React, Node, WordPress/headless; performance, accessibility, handover." },
  { slug: "website-design", title: "Website design", primary: "website design company", also: ["business website design", "professional website design", "responsive website design"], angle: "Design side for business sites: structure, copy, mobile-first layouts, brand, conversion; what a small business gets." },
  { slug: "ecommerce-development", title: "E-commerce development", primary: "ecommerce website development", also: ["online store development", "ecommerce development company", "woocommerce developer"], angle: "Online stores: Shopify, WooCommerce, custom; payments (Stripe, eSewa/Khalti in Nepal), shipping, inventory, product SEO." },
  { slug: "wordpress-development", title: "WordPress development", primary: "wordpress developer", also: ["wordpress website design", "wordpress agency", "custom wordpress theme"], angle: "Custom themes/blocks, speed, security hardening, plugin discipline, migrations, maintenance." },
  { slug: "mobile-app-development", title: "Mobile app development", primary: "mobile app development company", also: ["android app development", "ios app development", "mobile app developers", "app development company in nepal"], angle: "iOS/Android with Flutter or React Native vs native, store submission, backend, analytics, maintenance." },
  { slug: "software-development", title: "Custom software development", primary: "custom software development company", also: ["software development services", "bespoke software", "saas development"], angle: "Platforms, internal tools, APIs, integrations, SaaS, legacy migration; TypeScript, Python, Go, .NET." },
  { slug: "ai-development", title: "AI development", primary: "ai development company", also: ["ai chatbot development", "llm application development", "ai automation services"], angle: "LLM apps, RAG over company documents, document extraction, evaluation harness first, cost control, when not to use AI." },
  { slug: "seo-services", title: "SEO services", primary: "seo services", also: ["seo company", "technical seo", "aeo and geo services", "local seo"], angle: "Technical SEO first, content for buying intent, local SEO, AEO/GEO for AI answers, no bought links, reporting next to revenue." },
  { slug: "digital-marketing", title: "Digital marketing", primary: "digital marketing agency", also: ["google ads management", "social media marketing", "ppc management"], angle: "Paid search/social, email and lifecycle, tracking and attribution; ad accounts in client's name." },
  { slug: "cloud-devops", title: "Cloud and DevOps", primary: "devops services", also: ["cloud migration services", "ci/cd pipeline setup", "kubernetes consulting", "cloud infrastructure management"], angle: "AWS/Azure/GCP, Terraform, CI/CD under ten minutes, monitoring, on-call runbooks, cost reviews." },
  { slug: "ui-ux-design", title: "UI/UX design", primary: "ui ux design agency", also: ["ux design services", "product design", "user research"], angle: "Research, wireframes, prototypes tested with real users, design systems, accessibility." },
  { slug: "qa-testing", title: "QA and testing", primary: "software testing services", also: ["qa automation", "manual testing", "load testing"], angle: "Automated suites, regression before every release, load tests shaped like real traffic, device testing." },
  { slug: "cybersecurity", title: "Cybersecurity", primary: "cybersecurity services", also: ["website security audit", "penetration testing", "security hardening"], angle: "Code and infrastructure review, pen testing, hardening, incident plan, OWASP Top 10." },
  { slug: "data-analytics", title: "Data analytics and BI", primary: "business intelligence services", also: ["data analytics services", "power bi dashboards", "data warehouse"], angle: "Warehouses, pipelines, dashboards aimed at the questions leadership asks; GA4 and product analytics." },
  { slug: "managed-it-services", title: "Managed IT services", primary: "managed it services", also: ["it support", "website maintenance services", "it outsourcing"], angle: "Devices, accounts, licences, helpdesk, website and server maintenance, response times written into the agreement." }
];

export const LOCATIONS = [
  // Countries
  { slug: "nepal", type: "country", name: "Nepal", primary: "best website developer in nepal", also: ["web development company in nepal", "website design in nepal", "it company in nepal", "software company in nepal"], angle: "Home market. NPR pricing; eSewa, Khalti, Fonepay, ConnectIPS; .com.np domains; Nepali/English bilingual sites with Unicode; mobile-first audience; Facebook, TikTok, Viber and WhatsApp as enquiry channels; Individual Privacy Act 2075 (2018) and Electronic Transactions Act 2063 (2008); industries: tourism, hospitality, education consultancies, NGOs, retail." },
  { slug: "usa", type: "country", name: "USA", primary: "best website developer in usa", also: ["web development company usa", "hire web developers usa", "offshore web development for us companies"], angle: "Nepal is UTC+5:45 with no daylight saving; 9h45m ahead of US Eastern in summer (EDT) and 10h45m in winter (EST): Nepal evening overlaps US morning, and work continues overnight. ADA Title III website lawsuits and WCAG 2.1/2.2 AA; CCPA/CPRA and other state privacy laws; Stripe in the client's own account; USD contracts; white-label work for US agencies." },
  { slug: "australia", type: "country", name: "Australia", primary: "best website developer in australia", also: ["web developer australia", "web design australia", "offshore web development australia"], angle: "Nepal is 4h15m behind AEST (5h15m behind AEDT): Nepal morning is the Australian east-coast afternoon, so there is same-day overlap. Privacy Act 1988 and the Australian Privacy Principles; Spam Act 2003; consumer prices shown including GST; Disability Discrimination Act 1992 and WCAG; .com.au needs an Australian presence (ABN/ACN); Afterpay, Stripe, PayPal." },
  { slug: "canada", type: "country", name: "Canada", primary: "best website developer in canada", also: ["web development company canada", "web designer canada", "hire web developer canada"], angle: "Eastern and Pacific time; PIPEDA federally, Quebec Law 25, BC and Alberta PIPA; CASL makes consent for commercial email strict; AODA in Ontario (WCAG 2.0 AA for organisations with 50+ employees); English/French bilingual sites and Quebec's Charter of the French Language; CAD pricing." },
  { slug: "uk", type: "country", name: "UK", primary: "best website developer in uk", also: ["web development company uk", "web design agency uk", "website developer united kingdom"], angle: "Nepal is 4h45m ahead of BST and 5h45m ahead of GMT: Nepal afternoon is UK morning. UK GDPR, Data Protection Act 2018 and PECR cookie consent; Equality Act 2010 accessibility; .co.uk; VAT-inclusive consumer pricing; GBP." },
  { slug: "new-zealand", type: "country", name: "New Zealand", primary: "website developer new zealand", also: ["web design nz", "web development company nz", "affordable website nz"], angle: "Nepal is 6h15m behind NZST and 7h15m behind NZDT: NZ afternoon is Nepal morning. Privacy Act 2020; Unsolicited Electronic Messages Act 2007; GST-inclusive pricing; .co.nz and .nz; Te Reo Maori macrons in content; small-business heavy market." },
  { slug: "uae", type: "country", name: "UAE", primary: "website developer uae", also: ["web development company dubai", "website design company uae", "arabic website development"], angle: "UAE is UTC+4, Nepal 1h45m ahead, nearly identical working hours. Arabic/English bilingual sites with right-to-left layouts; UAE PDPL (Federal Decree-Law No. 45 of 2021) and DIFC/ADGM data protection regimes; gateways such as Telr, PayTabs, Network International and Stripe; large Nepali community in the UAE." },
  { slug: "singapore", type: "country", name: "Singapore", primary: "web developer singapore", also: ["web development company singapore", "website design singapore", "offshore developer singapore"], angle: "Singapore is UTC+8, Nepal 2h15m behind: almost full overlap. PDPA 2012 and the Do Not Call provisions; Spam Control Act; PayNow and Stripe; .sg domains; regional HQs and B2B; multilingual audiences (English, Chinese, Malay, Tamil)." },
  // Cities
  { slug: "kathmandu", type: "city", country: "nepal", name: "Kathmandu", primary: "website developer in kathmandu", also: ["web design company kathmandu", "it company in kathmandu", "website design kathmandu"], angle: "Capital and densest market. Thamel hotels and trekking agencies, Putalisadak education consultancies, restaurants and retail; heavy local competition in Google Maps and 'near me' searches; Google Business Profile, Nepali-language search, Facebook-first customers." },
  { slug: "lalitpur", type: "city", country: "nepal", name: "Lalitpur", primary: "website developer in lalitpur", also: ["web design lalitpur", "website design patan", "it company lalitpur"], angle: "Patan: heritage tourism, Patan metal and handicraft exporters selling abroad, cafes and restaurants in Jhamsikhel and Sanepa, many NGO and INGO offices around Pulchowk, Sanepa and Jawalakhel that need donor-ready, accessible sites." },
  { slug: "pokhara", type: "city", country: "nepal", name: "Pokhara", primary: "website developer in pokhara", also: ["web design pokhara", "hotel website pokhara", "website design company pokhara"], angle: "Tourism capital: Lakeside hotels and guesthouses, paragliding and adventure operators, Annapurna trekking; direct bookings vs OTA commission; multilingual visitors; seasonal demand; Pokhara International Airport (opened January 2023)." },
  { slug: "sydney", type: "city", country: "australia", name: "Sydney", primary: "website developer sydney", also: ["web design sydney", "web development company sydney", "affordable web developer sydney"], angle: "AEST/AEDT; trades, hospitality, professional services and startups; very competitive local SEO; Sydney agency rates vs offshore delivery; GST-inclusive pricing and Privacy Act obligations." },
  { slug: "melbourne", type: "city", country: "australia", name: "Melbourne", primary: "web developer melbourne", also: ["web design melbourne", "website development melbourne", "shopify developer melbourne"], angle: "Cafe and hospitality culture, fashion and retail e-commerce, creative industries; Shopify-heavy DTC brands; event-driven seasons; same time zone as Sydney." },
  { slug: "brisbane", type: "city", country: "australia", name: "Brisbane", primary: "web developer brisbane", also: ["web design brisbane", "website developer queensland", "brisbane web development company"], angle: "Queensland has no daylight saving, so Brisbane is UTC+10 all year and always 4h15m ahead of Nepal: the simplest overlap of any Australian city. Construction, trades, tourism, growing tech scene; 2032 Olympic and Paralympic Games preparation." },
  { slug: "toronto", type: "city", country: "canada", name: "Toronto", primary: "web developer toronto", also: ["web design toronto", "website development company toronto", "toronto web agency"], angle: "Eastern time; Ontario's AODA accessibility rules; finance, tech and professional services; very multilingual population; PIPEDA and CASL." },
  { slug: "vancouver", type: "city", country: "canada", name: "Vancouver", primary: "web developer vancouver", also: ["web design vancouver", "website developer bc", "vancouver web development company"], angle: "Pacific time: Nepal is 12h45m ahead of PDT, so work is asynchronous with short early/late overlap windows. BC's own PIPA for private-sector privacy; tech, film, tourism and outdoor brands; strong Asia-Pacific trade links." },
  { slug: "new-york", type: "city", country: "usa", name: "New York", primary: "web developer new york", also: ["nyc web design", "web development company new york", "new york website developer"], angle: "Eastern time; New York's SHIELD Act data-security duties; a large share of ADA website lawsuits are filed in New York federal courts; finance, media, retail and professional services; high local agency rates." },
  { slug: "los-angeles", type: "city", country: "usa", name: "Los Angeles", primary: "web developer los angeles", also: ["web design los angeles", "la web development company", "shopify developer los angeles"], angle: "Pacific time; CCPA/CPRA privacy obligations; entertainment, creative, DTC and e-commerce brands; video-heavy sites that still need to be fast; Spanish-language audiences." },
  { slug: "chicago", type: "city", country: "usa", name: "Chicago", primary: "web developer chicago", also: ["web design chicago", "chicago web development company", "b2b website developer chicago"], angle: "Central time; manufacturing, logistics, B2B and professional services; Illinois BIPA if a product touches biometrics; dealer portals, quote forms and ERP integrations." },
  { slug: "london", type: "city", country: "uk", name: "London", primary: "web developer london", also: ["web design london", "web development agency london", "london website developer"], angle: "GMT/BST; fintech and professional services; UK GDPR, PECR cookie consent and the ICO; FCA-regulated firms' financial promotion rules; high London agency day rates vs offshore delivery." },
  { slug: "dubai", type: "city", country: "uae", name: "Dubai", primary: "web developer dubai", also: ["website design company dubai", "web development dubai", "arabic website developer dubai"], angle: "Gulf Standard Time (UTC+4); Arabic/English right-to-left sites; real estate, hospitality, retail and e-commerce; DIFC Data Protection Law 2020 for DIFC firms, PDPL elsewhere; WhatsApp-first enquiries." }
];

export const INDUSTRIES = [
  { slug: "hospitality", title: "Hotels and restaurants", primary: "hotel website design", also: ["restaurant website development", "hotel booking engine", "resort website"], angle: "Direct bookings vs OTA commission, booking engines, menus, table reservations, Google Hotel listings, photos that load fast." },
  { slug: "travel-and-tourism", title: "Travel and tourism", primary: "travel agency website development", also: ["trekking company website", "tour operator website", "travel booking website"], angle: "Trip pages that answer every question, itinerary structure, deposits online, reviews, multilingual; Nepal trekking context." },
  { slug: "healthcare", title: "Healthcare", primary: "healthcare website development", also: ["clinic website design", "hospital website", "doctor appointment app"], angle: "Appointment booking, doctor profiles, patient privacy, accessibility, trustworthy medical content (YMYL)." },
  { slug: "education", title: "Education", primary: "education website development", also: ["school website design", "education consultancy website", "lms development"], angle: "Schools, colleges, training institutes and study-abroad consultancies; admissions funnels, course pages, LMS, parent portals." },
  { slug: "real-estate", title: "Real estate", primary: "real estate website development", also: ["property listing website", "real estate portal development", "realtor website design"], angle: "Listings with search and maps, lead capture, CRM integration, property schema, fast image galleries." },
  { slug: "retail-and-ecommerce", title: "Retail and e-commerce", primary: "ecommerce website for retail", also: ["online shop for retail store", "inventory integration", "omnichannel retail website"], angle: "Moving a physical shop online: catalog, stock sync with POS, payments, delivery, returns, product SEO." },
  { slug: "nonprofits", title: "NGOs and nonprofits", primary: "ngo website development", also: ["nonprofit website design", "donation website", "ingo website nepal"], angle: "Donor-ready reporting, donations, accessibility, bilingual content, low-bandwidth performance, grant-funded budgets." },
  { slug: "startups-and-saas", title: "Startups and SaaS", primary: "saas development company", also: ["startup app development", "mvp development company", "saas website design"], angle: "MVP scope, multi-tenancy, billing, onboarding, marketing site plus product, investor-ready demos." },
  { slug: "professional-services", title: "Professional services", primary: "website for law firm and accounting firm", also: ["consulting firm website", "law firm website design", "accounting firm website"], angle: "Authority content, client portals, secure document exchange, booking consultations, compliance with professional advertising rules." }
];

// Blog posts. `n` is the order in the plan and the post's `order` field.
// Technology pages own "<technology> development company" plus the "hire
// <technology> developers" variant. Service pages own the broader query
// (web development company, devops services...), so the two never compete.
export const TECHNOLOGIES = [
  { slug: "nextjs", title: "Next.js", primary: "next.js development company", also: ["hire next.js developers", "next.js agency", "next.js website development"], angle: "App Router, server rendering and static generation for marketing sites and web apps; SEO and Core Web Vitals; headless CMS; when WordPress is the better call." },
  { slug: "react", title: "React", primary: "react development company", also: ["hire react developers", "react js development services", "react web app development"], angle: "Interactive front ends and dashboards; state, forms, data fetching, design systems, testing; React vs Next.js." },
  { slug: "nodejs", title: "Node.js", primary: "node.js development company", also: ["hire node.js developers", "node.js api development", "node js backend development"], angle: "APIs, integrations, real-time features and background jobs in TypeScript; Express/Fastify/NestJS; Node vs Python vs Go." },
  { slug: "python", title: "Python", primary: "python development company", also: ["hire python developers", "django development", "fastapi development"], angle: "Django and FastAPI back ends, data pipelines, automation scripts and AI/LLM work; when Python is and is not the right back end." },
  { slug: "flutter", title: "Flutter", primary: "flutter app development company", also: ["hire flutter developers", "flutter app development services", "cross-platform app development"], angle: "One Dart codebase for iOS and Android; custom UI, offline, payments; store release; Flutter vs React Native." },
  { slug: "react-native", title: "React Native", primary: "react native app development company", also: ["hire react native developers", "react native development services", "expo app development"], angle: "Cross-platform apps sharing code and people with a React web team; Expo, EAS, OTA updates; when native is the better choice." },
  { slug: "shopify", title: "Shopify", primary: "shopify development agency", also: ["shopify experts", "shopify store setup", "shopify theme development"], angle: "Store setup and migration, Online Store 2.0 themes, apps, markets and payments; when Shopify beats WooCommerce or custom." },
  { slug: "aws", title: "AWS", primary: "aws consulting services", also: ["aws cloud migration", "hire aws developers", "aws cost optimization"], angle: "Account structure, infrastructure as code, containers and serverless, cost control and backups on AWS; AWS vs Azure vs Google Cloud." }
];

export const POSTS = [
  // Nepal business
  { n: 1, slug: "website-cost-in-nepal", category: "nepal", title: "How Much Does a Website Cost in Nepal in 2026?", primary: "website cost in nepal", also: ["website price in nepal", "website design price in nepal", "ecommerce website cost nepal"] },
  { n: 2, slug: "best-website-developer-in-nepal-checklist", category: "nepal", title: "How to Choose the Best Website Developer in Nepal: A 15-Point Checklist", primary: "best website developer in nepal", also: ["web development company in nepal", "how to choose web developer nepal", "top it company nepal"] },
  { n: 3, slug: "esewa-khalti-fonepay-integration", category: "nepal", title: "eSewa, Khalti and Fonepay Integration: Taking Online Payments on a Nepali Website", primary: "esewa integration", also: ["khalti payment gateway integration", "payment gateway in nepal", "fonepay qr website"] },
  { n: 4, slug: "start-ecommerce-website-in-nepal", category: "nepal", title: "How to Start an E-commerce Website in Nepal: Platform, Payments and Delivery", primary: "ecommerce website in nepal", also: ["online store nepal", "ecommerce development nepal", "sell online in nepal"] },
  { n: 5, slug: "seo-in-nepal", category: "nepal", title: "SEO in Nepal: How Nepali Businesses Rank on Google", primary: "seo in nepal", also: ["seo company in nepal", "seo services nepal", "google ranking nepal"] },
  { n: 6, slug: "com-np-domain-registration", category: "nepal", title: ".com.np Domain Registration: How It Works and When to Use .com Instead", primary: "com.np domain registration", also: ["free np domain", "np domain registration process", ".com vs .com.np"] },
  { n: 7, slug: "trekking-agency-website-nepal", category: "nepal", title: "Websites for Trekking and Tour Operators in Nepal That Win International Bookings", primary: "trekking agency website", also: ["travel agency website nepal", "tour operator website design", "trekking company website nepal"] },
  { n: 8, slug: "hotel-website-direct-bookings-nepal", category: "nepal", title: "Hotel Websites in Nepal: Getting Direct Bookings and Paying Less OTA Commission", primary: "hotel website nepal", also: ["hotel booking engine nepal", "direct booking website", "hotel website design nepal"] },
  { n: 9, slug: "nepali-english-bilingual-website", category: "nepal", title: "Building a Nepali-English Bilingual Website: Unicode, Fonts and SEO", primary: "nepali language website", also: ["bilingual website nepal", "nepali unicode website", "nepali font for website"] },
  { n: 10, slug: "outsource-software-development-to-nepal", category: "nepal", title: "Why Companies Outsource Software Development to Nepal (and What to Watch For)", primary: "outsource software development to nepal", also: ["it outsourcing nepal", "software outsourcing company nepal", "offshore developers nepal"] },
  { n: 11, slug: "education-consultancy-website-nepal", category: "nepal", title: "Websites for Education Consultancies in Nepal: Turning Enquiries Into Enrolled Students", primary: "education consultancy website nepal", also: ["study abroad consultancy website", "consultancy website design nepal", "student enquiry system"] },
  { n: 12, slug: "digital-marketing-small-business-nepal", category: "nepal", title: "Digital Marketing for Small Businesses in Nepal: A Budget Plan That Works", primary: "digital marketing in nepal", also: ["social media marketing nepal", "facebook ads nepal", "digital marketing agency nepal"] },
  // Costs and hiring
  { n: 13, slug: "website-cost-australia", category: "costs-and-hiring", title: "Website Development Cost in Australia (2026): Agency, Freelancer or Offshore?", primary: "website cost australia", also: ["web design cost australia", "how much does a website cost australia", "web developer rates australia"] },
  { n: 14, slug: "website-cost-usa", category: "costs-and-hiring", title: "How Much Does a Website Cost in the USA in 2026?", primary: "how much does a website cost usa", also: ["website cost for small business usa", "web developer hourly rate usa", "website design pricing usa"] },
  { n: 15, slug: "website-cost-canada", category: "costs-and-hiring", title: "Website Design Cost in Canada: A 2026 Price Guide", primary: "website design cost canada", also: ["how much does a website cost in canada", "web developer rates canada", "small business website cost canada"] },
  { n: 16, slug: "website-cost-uk", category: "costs-and-hiring", title: "Website Cost in the UK (2026): What Small Businesses Actually Pay", primary: "website cost uk", also: ["how much does a website cost uk", "web design prices uk", "web developer day rate uk"] },
  { n: 17, slug: "offshore-vs-nearshore-vs-onshore-development", category: "costs-and-hiring", title: "Offshore vs Nearshore vs Onshore Development: An Honest Comparison", primary: "offshore vs nearshore development", also: ["offshore software development", "onshore vs offshore", "nearshore outsourcing"] },
  { n: 18, slug: "how-to-hire-a-remote-web-developer", category: "costs-and-hiring", title: "How to Hire a Remote Web Developer Without Getting Burned", primary: "hire remote web developer", also: ["how to hire a web developer", "hire offshore developer", "remote developer interview questions"] },
  { n: 19, slug: "freelancer-vs-web-development-agency", category: "costs-and-hiring", title: "Freelancer vs Web Development Agency: Which Should You Hire?", primary: "freelancer vs agency web development", also: ["hire freelancer or agency", "web agency vs freelancer cost", "should i hire a web developer"] },
  { n: 20, slug: "working-across-time-zones-offshore-team", category: "costs-and-hiring", title: "Working With an Offshore Development Team Across Time Zones", primary: "offshore team time zone", also: ["nepal time zone overlap", "async collaboration remote team", "managing offshore developers"] },
  { n: 21, slug: "how-to-compare-web-development-quotes", category: "costs-and-hiring", title: "How to Compare Web Development Quotes and Proposals", primary: "compare web development quotes", also: ["web development proposal", "website quote checklist", "what should a website proposal include"] },
  { n: 22, slug: "white-label-web-development", category: "costs-and-hiring", title: "White-Label Web Development for Agencies: How the Partnership Works", primary: "white label web development", also: ["white label agency partner", "outsourced web development for agencies", "white label wordpress development"] },
  // Web development
  { n: 23, slug: "nextjs-vs-wordpress", category: "web-development", title: "Next.js vs WordPress for Business Websites in 2026", primary: "nextjs vs wordpress", also: ["wordpress or custom website", "headless wordpress", "best platform for business website"] },
  { n: 24, slug: "shopify-vs-woocommerce-vs-custom-ecommerce", category: "web-development", title: "Shopify vs WooCommerce vs Custom E-commerce: How to Choose", primary: "shopify vs woocommerce", also: ["custom ecommerce vs shopify", "best ecommerce platform small business", "woocommerce or shopify"] },
  { n: 25, slug: "core-web-vitals-explained", category: "web-development", title: "Core Web Vitals Explained for Business Owners: LCP, INP and CLS", primary: "core web vitals", also: ["what is lcp inp cls", "improve page speed", "core web vitals seo"] },
  { n: 26, slug: "website-redesign-without-losing-seo", category: "web-development", title: "Website Redesign Checklist: How to Relaunch Without Losing Rankings", primary: "website redesign checklist", also: ["redesign without losing seo", "website migration seo", "301 redirect plan"] },
  { n: 27, slug: "website-maintenance-guide", category: "web-development", title: "Website Maintenance: What It Involves and What It Should Cost", primary: "website maintenance cost", also: ["website maintenance services", "what is website maintenance", "wordpress maintenance plan"] },
  { n: 28, slug: "how-long-to-build-a-website", category: "web-development", title: "How Long Does It Take to Build a Website? Realistic Timelines by Project Type", primary: "how long does it take to build a website", also: ["website development timeline", "website project schedule", "ecommerce website timeline"] },
  { n: 29, slug: "website-project-brief-template", category: "web-development", title: "How to Write a Website Project Brief (With a Free Template)", primary: "website project brief", also: ["website brief template", "web design brief", "website requirements document"] },
  { n: 30, slug: "website-vs-web-application", category: "web-development", title: "Website vs Web Application: Which Does Your Business Need?", primary: "website vs web application", also: ["web app vs website", "do i need a web app", "web application examples"] },
  { n: 31, slug: "landing-page-conversion-checklist", category: "web-development", title: "Landing Page Conversion Checklist: 15 Fixes That Move the Numbers", primary: "landing page conversion", also: ["landing page best practices", "improve conversion rate", "landing page checklist"] },
  { n: 32, slug: "pwa-vs-native-app", category: "web-development", title: "Progressive Web App vs Native App: Which Should a Small Business Build?", primary: "pwa vs native app", also: ["progressive web app benefits", "pwa for small business", "web app or mobile app"] },
  { n: 33, slug: "headless-cms-guide", category: "web-development", title: "Headless CMS Explained: When It Is Worth It and When It Is Not", primary: "headless cms", also: ["headless cms vs wordpress", "what is a headless cms", "best headless cms"] },
  // SEO and marketing
  { n: 34, slug: "answer-engine-optimization-aeo", category: "seo-and-marketing", title: "Answer Engine Optimization (AEO): How to Get Your Business Cited in AI Answers", primary: "answer engine optimization", also: ["what is aeo", "aeo vs seo", "optimize for ai overviews"] },
  { n: 35, slug: "generative-engine-optimization-geo", category: "seo-and-marketing", title: "Generative Engine Optimization (GEO): Getting Your Brand Into ChatGPT, Gemini and Perplexity", primary: "generative engine optimization", also: ["what is geo seo", "rank in chatgpt", "llms.txt"] },
  { n: 36, slug: "local-seo-google-business-profile", category: "seo-and-marketing", title: "Local SEO: Google Business Profile Optimization Step by Step", primary: "google business profile optimization", also: ["local seo checklist", "rank in google maps", "near me seo"] },
  { n: 37, slug: "technical-seo-audit-checklist", category: "seo-and-marketing", title: "Technical SEO Audit Checklist for 2026", primary: "technical seo audit checklist", also: ["seo audit", "crawl errors", "indexing issues"] },
  { n: 38, slug: "schema-markup-for-small-business", category: "seo-and-marketing", title: "Schema Markup for Small Business Websites: What to Add First", primary: "schema markup for small business", also: ["local business schema", "structured data seo", "json-ld examples"] },
  { n: 39, slug: "international-seo-guide", category: "seo-and-marketing", title: "International SEO: Ranking in the US, UK, Australia and Canada From One Website", primary: "international seo", also: ["hreflang guide", "multi country seo", "ccTLD vs subfolder"] },
  { n: 40, slug: "google-ads-vs-seo", category: "seo-and-marketing", title: "Google Ads vs SEO: Where Should a Small Business Spend First?", primary: "google ads vs seo", also: ["ppc vs seo", "should i do seo or ads", "small business marketing budget"] },
  { n: 41, slug: "content-marketing-for-it-companies", category: "seo-and-marketing", title: "B2B Content Marketing for IT and Professional Services Firms", primary: "b2b content marketing", also: ["content marketing for it companies", "b2b seo content", "thought leadership content"] },
  { n: 42, slug: "email-marketing-for-small-business", category: "seo-and-marketing", title: "Email Marketing for Small Businesses: Consent, Deliverability and Your First Campaigns", primary: "email marketing for small business", also: ["double opt in", "email deliverability spf dkim dmarc", "email list building"] },
  // Software, AI and cloud
  { n: 43, slug: "custom-software-development-cost", category: "costs-and-hiring", title: "Custom Software Development Cost: How Projects Are Actually Priced", primary: "custom software development cost", also: ["software development pricing", "fixed price vs time and materials", "cost to build software"] },
  { n: 44, slug: "mobile-app-development-cost", category: "costs-and-hiring", title: "Mobile App Development Cost in 2026: Native, Flutter or React Native?", primary: "mobile app development cost", also: ["app development cost", "flutter vs react native", "cost to build an app"] },
  { n: 45, slug: "ai-chatbot-for-business-website", category: "software-and-ai", title: "AI Chatbots for Business Websites: What Works and What to Avoid", primary: "ai chatbot for business website", also: ["ai customer support chatbot", "chatbot development", "website chatbot"] },
  { n: 46, slug: "rag-explained-for-business", category: "software-and-ai", title: "Retrieval-Augmented Generation (RAG) Explained for Business Leaders", primary: "retrieval augmented generation", also: ["what is rag ai", "rag vs fine tuning", "ai on company documents"] },
  { n: 47, slug: "mvp-development-guide", category: "software-and-ai", title: "How to Build an MVP: Scope, Budget and the First 90 Days", primary: "mvp development", also: ["how to build an mvp", "mvp cost", "minimum viable product examples"] },
  { n: 48, slug: "aws-vs-azure-vs-google-cloud", category: "software-and-ai", title: "AWS vs Azure vs Google Cloud for Small and Mid-Size Companies", primary: "aws vs azure vs google cloud", also: ["best cloud provider for small business", "cloud cost comparison", "cloud hosting for startups"] },
  { n: 49, slug: "legacy-system-modernization", category: "software-and-ai", title: "Legacy System Modernization: Rewrite, Refactor or Replace?", primary: "legacy system modernization", also: ["legacy application modernization", "rewrite vs refactor", "software modernization strategy"] },
  { n: 50, slug: "website-security-checklist", category: "web-development", title: "Website Security Checklist for Small Businesses", primary: "website security checklist", also: ["how to secure a website", "wordpress security", "small business cybersecurity"] }
];

export const PLANNED_PATHS = new Set([
  ...STATIC_ROUTES,
  ...SERVICES.map((s) => `/services/${s.slug}`),
  ...LOCATIONS.map((l) => `/website-developer/${l.slug}`),
  ...INDUSTRIES.map((i) => `/industries/${i.slug}`),
  ...TECHNOLOGIES.map((t) => `/technologies/${t.slug}`),
  ...POSTS.map((p) => `/blog/${p.slug}`),
  "/blog/category/nepal",
  "/blog/category/costs-and-hiring",
  "/blog/category/web-development",
  "/blog/category/seo-and-marketing",
  "/blog/category/software-and-ai"
]);
